
services:
  dallosh_bot:
    image: dallosh/bot:0.1.0
    build:
      context: ./servers/dallosh_bot
      network: host
    container_name: dallosh_bot
    restart: always
    network_mode: "host"  # Use host network directly
    # Remove all ports mapping when using host network
    # ports:
    #   # Main application port
    #   - "7860:7860"
    #   # STUN/TURN protocol ports (required for WebRTC NAT traversal)
    #   - "3478:3478/tcp"
    #   - "3478:3478/udp"
    #   - "5349:5349/tcp"
    #   - "5349:5349/udp"
    # #   # WebRTC media ports (smaller, focused range)
    #   - "32768-65535:32768-65535/udp"  # Full dynamic range
    #   - "32768-65535:32768-65535/tcp"  # Full dynamic range
    volumes:
      - ./servers/dallosh_bot/models:/app/models
    env_file:
      - ./servers/dallosh_bot/.env
    # networks:
    #   - dallosh_net
    # extra_hosts:  # we should this as sometimes linux does not expose host.docker.internal by default
    #   - "host.docker.internal:172.17.0.1"
    # Simplified health check - just check if the process is running
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python.*main.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  dallosh_functions:
    image: dallosh/functions:0.1.0
    build:
      context: ./servers/dallosh_functions
      network: host
    container_name: dallosh_functions
    restart: always
    env_file:
      - ./servers/dallosh_functions/.env
    networks:
      - dallosh_net
    extra_hosts:
      - "sodular_server:172.17.0.1"

  dallosh_web:
    image: dallosh/web:0.1.0
    build:
      context: ./clients/dallosh_web
      network: host
    container_name: dallosh_web
    restart: always
    ports:
      - "3005:3005"
    env_file:
      - ./clients/dallosh_web/.env.production
    depends_on:
      dallosh_bot:
        condition: service_started  # Changed from service_healthy to service_started
      dallosh_functions:
        condition: service_started
    networks:
      - dallosh_net
    extra_hosts:
      - "sodular_server:172.17.0.1"

networks:
  dallosh_net:
    driver: bridge

